backend:
  name: git-gateway
  repo: "billiamchoi/billiamchoi.github.io" # GitHub 사용자명과 저장소명
  branch: master # 콘텐츠가 저장될 브랜치

media_folder: "assets/img" # Folder where images will be uploaded
public_folder: "/assets/img" # Path to access images in posts

collections:
  - name: "bugs"
    label: "Bugs"
    folder: "_posts/Bugs"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          dateFormat: "YYYY-MM-DD",
          timeFormat: "HH:mm:ss Z",
          default: "{{now}}",
        }
      - {
          label: "Categories",
          name: "categories",
          widget: "hidden",
          default: bugs,
        }
      - { label: "Keyword", name: "keyword", widget: "list", allow_add: true }
      - {
          label: "Tags",
          name: "tags",
          widget: "select",
          multiple: true,
          options: [github, blog, Front-End, jekyll, html, css],
        }
      - {
          label: "Image Tag",
          name: "img-tag",
          widget: "select",
          options: [blog, github, jekyll, html, css, study],
        }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "develop"
    label: "Develop"
    folder: "_posts/Develop"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          dateFormat: "YYYY-MM-DD",
          timeFormat: "HH:mm:ss Z",
          default: "{{now}}",
        }
      - {
          label: "Categories",
          name: "categories",
          widget: "hidden",
          default: develop,
        }
      - { label: "Keyword", name: "keyword", widget: "list", allow_add: true }
      - {
          label: "Tags",
          name: "tags",
          widget: "select",
          multiple: true,
          options: [github, blog, Front-End, jekyll, html, css],
        }
      - {
          label: "Image Tag",
          name: "img-tag",
          widget: "select",
          options: [blog, github, jekyll, html, css, study],
        }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "study"
    label: "Study"
    folder: "_posts/Study"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          dateFormat: "YYYY-MM-DD",
          timeFormat: "HH:mm:ss Z",
          default: "{{now}}",
        }
      - {
          label: "Categories",
          name: "categories",
          widget: "hidden",
          default: study,
        }
      - { label: "Keyword", name: "keyword", widget: "list", allow_add: true }
      - {
          label: "Tags",
          name: "tags",
          widget: "select",
          multiple: true,
          options: [github, blog, Front-End, jekyll, html, css],
        }
      - {
          label: "Image Tag",
          name: "img-tag",
          widget: "select",
          options: [blog, github, jekyll, html, css, study],
        }
      - { label: "Body", name: "body", widget: "markdown" }
